# coding: utf-8

"""
    API Reference

    Sentry Public API  # noqa: E501

    The version of the OpenAPI document: v0
    Contact: partners@sentry.io
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.api_0_organizations_organization_slug_events_.get import QueryDiscoverEventsInTableFormat


class DiscoverApi(
    QueryDiscoverEventsInTableFormat,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
