# coding: utf-8

"""
    API Reference

    Sentry Public API  # noqa: E501

    The version of the OpenAPI document: v0
    Contact: partners@sentry.io
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.monitor_list import MonitorList
from openapi_client import configuration


class TestMonitorList(unittest.TestCase):
    """MonitorList unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
