# coding: utf-8

"""
    API Reference

    Sentry Public API  # noqa: E501

    The version of the OpenAPI document: v0
    Contact: partners@sentry.io
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.monitor_alert_rule_target_validator import MonitorAlertRuleTargetValidator
from openapi_client import configuration


class TestMonitorAlertRuleTargetValidator(unittest.TestCase):
    """MonitorAlertRuleTargetValidator unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
