# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from openapi_client.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    API_0_ORGANIZATION_ORGANIZATION_SLUG_MONITORS_MONITOR_SLUG_CHECKINS_ = "/api/0/organization/{organization_slug}/monitors/{monitor_slug}/checkins/"
    API_0_ORGANIZATION_ORGANIZATION_SLUG_MONITORS_MONITOR_SLUG_CHECKINS_CHECKIN_ID_ = "/api/0/organization/{organization_slug}/monitors/{monitor_slug}/checkins/{checkin_id}/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_EVENTS_ = "/api/0/organizations/{organization_slug}/events/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_MEMBERS_MEMBER_ID_ = "/api/0/organizations/{organization_slug}/members/{member_id}/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_MONITORS_ = "/api/0/organizations/{organization_slug}/monitors/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_MONITORS_MONITOR_SLUG_ = "/api/0/organizations/{organization_slug}/monitors/{monitor_slug}/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_PROJECTS_ = "/api/0/organizations/{organization_slug}/projects/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SCIM_V2_GROUPS = "/api/0/organizations/{organization_slug}/scim/v2/Groups"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SCIM_V2_GROUPS_TEAM_ID = "/api/0/organizations/{organization_slug}/scim/v2/Groups/{team_id}"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SCIM_V2_USERS = "/api/0/organizations/{organization_slug}/scim/v2/Users"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SCIM_V2_USERS_MEMBER_ID = "/api/0/organizations/{organization_slug}/scim/v2/Users/{member_id}"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_STATS_V2_ = "/api/0/organizations/{organization_slug}/stats_v2/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_EVENTS_EVENT_ID_SOURCEMAPDEBUG_ = "/api/0/projects/{organization_slug}/{project_slug}/events/{event_id}/source-map-debug/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_TEAMS_ = "/api/0/organizations/{organization_slug}/teams/"
    API_0_TEAMS_ORGANIZATION_SLUG_TEAM_SLUG_ = "/api/0/teams/{organization_slug}/{team_slug}/"
    API_0_TEAMS_ORGANIZATION_SLUG_TEAM_SLUG_PROJECTS_ = "/api/0/teams/{organization_slug}/{team_slug}/projects/"
    API_0_TEAMS_ORGANIZATION_SLUG_TEAM_SLUG_STATS_ = "/api/0/teams/{organization_slug}/{team_slug}/stats/"
    API_0_ORGANIZATIONS_ = "/api/0/organizations/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_EVENTIDS_EVENT_ID_ = "/api/0/organizations/{organization_slug}/eventids/{event_id}/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_ = "/api/0/organizations/{organization_slug}/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_REPOS_ = "/api/0/organizations/{organization_slug}/repos/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_REPOS_REPO_ID_COMMITS_ = "/api/0/organizations/{organization_slug}/repos/{repo_id}/commits/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_STATS_ = "/api/0/organizations/{organization_slug}/stats/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SESSIONS_ = "/api/0/organizations/{organization_slug}/sessions/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_USERS_ = "/api/0/organizations/{organization_slug}/users/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SHORTIDS_SHORT_ID_ = "/api/0/organizations/{organization_slug}/shortids/{short_id}/"
    API_0_PROJECTS_ = "/api/0/projects/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_ = "/api/0/projects/{organization_slug}/{project_slug}/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_FILES_DSYMS_ = "/api/0/projects/{organization_slug}/{project_slug}/files/dsyms/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_USERS_ = "/api/0/projects/{organization_slug}/{project_slug}/users/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_TAGS_KEY_VALUES_ = "/api/0/projects/{organization_slug}/{project_slug}/tags/{key}/values/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_STATS_ = "/api/0/projects/{organization_slug}/{project_slug}/stats/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_USERFEEDBACK_ = "/api/0/projects/{organization_slug}/{project_slug}/user-feedback/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_KEYS_ = "/api/0/projects/{organization_slug}/{project_slug}/keys/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_KEYS_KEY_ID_ = "/api/0/projects/{organization_slug}/{project_slug}/keys/{key_id}/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_HOOKS_ = "/api/0/projects/{organization_slug}/{project_slug}/hooks/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_HOOKS_HOOK_ID_ = "/api/0/projects/{organization_slug}/{project_slug}/hooks/{hook_id}/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_EVENTS_EVENT_ID_ = "/api/0/projects/{organization_slug}/{project_slug}/events/{event_id}/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_EVENTS_ = "/api/0/projects/{organization_slug}/{project_slug}/events/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_ISSUES_ = "/api/0/projects/{organization_slug}/{project_slug}/issues/"
    API_0_ISSUES_ISSUE_ID_TAGS_KEY_VALUES_ = "/api/0/issues/{issue_id}/tags/{key}/values/"
    API_0_ISSUES_ISSUE_ID_TAGS_KEY_ = "/api/0/issues/{issue_id}/tags/{key}/"
    API_0_ISSUES_ISSUE_ID_HASHES_ = "/api/0/issues/{issue_id}/hashes/"
    API_0_ISSUES_ISSUE_ID_EVENTS_OLDEST_ = "/api/0/issues/{issue_id}/events/oldest/"
    API_0_ISSUES_ISSUE_ID_EVENTS_LATEST_ = "/api/0/issues/{issue_id}/events/latest/"
    API_0_ISSUES_ISSUE_ID_EVENTS_ = "/api/0/issues/{issue_id}/events/"
    API_0_ISSUES_ISSUE_ID_ = "/api/0/issues/{issue_id}/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_ = "/api/0/organizations/{organization_slug}/releases/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_ = "/api/0/organizations/{organization_slug}/releases/{version}/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_FILES_ = "/api/0/organizations/{organization_slug}/releases/{version}/files/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_RELEASES_VERSION_FILES_ = "/api/0/projects/{organization_slug}/{project_slug}/releases/{version}/files/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_FILES_FILE_ID_ = "/api/0/organizations/{organization_slug}/releases/{version}/files/{file_id}/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_RELEASES_VERSION_FILES_FILE_ID_ = "/api/0/projects/{organization_slug}/{project_slug}/releases/{version}/files/{file_id}/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_COMMITS_ = "/api/0/organizations/{organization_slug}/releases/{version}/commits/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_RELEASES_VERSION_COMMITS_ = "/api/0/projects/{organization_slug}/{project_slug}/releases/{version}/commits/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_COMMITFILES_ = "/api/0/organizations/{organization_slug}/releases/{version}/commitfiles/"
    API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_RELEASES_VERSION_RESOLVED_ = "/api/0/projects/{organization_slug}/{project_slug}/releases/{version}/resolved/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_DEPLOYS_ = "/api/0/organizations/{organization_slug}/releases/{version}/deploys/"
    API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SENTRYAPPINSTALLATIONS_ = "/api/0/organizations/{organization_slug}/sentry-app-installations/"
    API_0_SENTRYAPPINSTALLATIONS_UUID_EXTERNALISSUES_ = "/api/0/sentry-app-installations/{uuid}/external-issues/"
    API_0_SENTRYAPPINSTALLATIONS_UUID_EXTERNALISSUES_EXTERNAL_ISSUE_ID_ = "/api/0/sentry-app-installations/{uuid}/external-issues/{external_issue_id}/"
