import typing_extensions

from openapi_client.paths import PathValues
from openapi_client.apis.paths.api_0_organization_organization_slug_monitors_monitor_slug_checkins_ import Api0OrganizationOrganizationSlugMonitorsMonitorSlugCheckins
from openapi_client.apis.paths.api_0_organization_organization_slug_monitors_monitor_slug_checkins_checkin_id_ import Api0OrganizationOrganizationSlugMonitorsMonitorSlugCheckinsCheckinId
from openapi_client.apis.paths.api_0_organizations_organization_slug_events_ import Api0OrganizationsOrganizationSlugEvents
from openapi_client.apis.paths.api_0_organizations_organization_slug_members_member_id_ import Api0OrganizationsOrganizationSlugMembersMemberId
from openapi_client.apis.paths.api_0_organizations_organization_slug_monitors_ import Api0OrganizationsOrganizationSlugMonitors
from openapi_client.apis.paths.api_0_organizations_organization_slug_monitors_monitor_slug_ import Api0OrganizationsOrganizationSlugMonitorsMonitorSlug
from openapi_client.apis.paths.api_0_organizations_organization_slug_projects_ import Api0OrganizationsOrganizationSlugProjects
from openapi_client.apis.paths.api_0_organizations_organization_slug_scim_v2_groups import Api0OrganizationsOrganizationSlugScimV2Groups
from openapi_client.apis.paths.api_0_organizations_organization_slug_scim_v2_groups_team_id import Api0OrganizationsOrganizationSlugScimV2GroupsTeamId
from openapi_client.apis.paths.api_0_organizations_organization_slug_scim_v2_users import Api0OrganizationsOrganizationSlugScimV2Users
from openapi_client.apis.paths.api_0_organizations_organization_slug_scim_v2_users_member_id import Api0OrganizationsOrganizationSlugScimV2UsersMemberId
from openapi_client.apis.paths.api_0_organizations_organization_slug_stats_v2_ import Api0OrganizationsOrganizationSlugStatsV2
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_events_event_id_source_map_debug_ import Api0ProjectsOrganizationSlugProjectSlugEventsEventIdSourceMapDebug
from openapi_client.apis.paths.api_0_organizations_organization_slug_teams_ import Api0OrganizationsOrganizationSlugTeams
from openapi_client.apis.paths.api_0_teams_organization_slug_team_slug_ import Api0TeamsOrganizationSlugTeamSlug
from openapi_client.apis.paths.api_0_teams_organization_slug_team_slug_projects_ import Api0TeamsOrganizationSlugTeamSlugProjects
from openapi_client.apis.paths.api_0_teams_organization_slug_team_slug_stats_ import Api0TeamsOrganizationSlugTeamSlugStats
from openapi_client.apis.paths.api_0_organizations_ import Api0Organizations
from openapi_client.apis.paths.api_0_organizations_organization_slug_eventids_event_id_ import Api0OrganizationsOrganizationSlugEventidsEventId
from openapi_client.apis.paths.api_0_organizations_organization_slug_ import Api0OrganizationsOrganizationSlug
from openapi_client.apis.paths.api_0_organizations_organization_slug_repos_ import Api0OrganizationsOrganizationSlugRepos
from openapi_client.apis.paths.api_0_organizations_organization_slug_repos_repo_id_commits_ import Api0OrganizationsOrganizationSlugReposRepoIdCommits
from openapi_client.apis.paths.api_0_organizations_organization_slug_stats_ import Api0OrganizationsOrganizationSlugStats
from openapi_client.apis.paths.api_0_organizations_organization_slug_sessions_ import Api0OrganizationsOrganizationSlugSessions
from openapi_client.apis.paths.api_0_organizations_organization_slug_users_ import Api0OrganizationsOrganizationSlugUsers
from openapi_client.apis.paths.api_0_organizations_organization_slug_shortids_short_id_ import Api0OrganizationsOrganizationSlugShortidsShortId
from openapi_client.apis.paths.api_0_projects_ import Api0Projects
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_ import Api0ProjectsOrganizationSlugProjectSlug
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_files_dsyms_ import Api0ProjectsOrganizationSlugProjectSlugFilesDsyms
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_users_ import Api0ProjectsOrganizationSlugProjectSlugUsers
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_tags_key_values_ import Api0ProjectsOrganizationSlugProjectSlugTagsKeyValues
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_stats_ import Api0ProjectsOrganizationSlugProjectSlugStats
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_user_feedback_ import Api0ProjectsOrganizationSlugProjectSlugUserFeedback
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_keys_ import Api0ProjectsOrganizationSlugProjectSlugKeys
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_keys_key_id_ import Api0ProjectsOrganizationSlugProjectSlugKeysKeyId
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_hooks_ import Api0ProjectsOrganizationSlugProjectSlugHooks
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_hooks_hook_id_ import Api0ProjectsOrganizationSlugProjectSlugHooksHookId
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_events_event_id_ import Api0ProjectsOrganizationSlugProjectSlugEventsEventId
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_events_ import Api0ProjectsOrganizationSlugProjectSlugEvents
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_issues_ import Api0ProjectsOrganizationSlugProjectSlugIssues
from openapi_client.apis.paths.api_0_issues_issue_id_tags_key_values_ import Api0IssuesIssueIdTagsKeyValues
from openapi_client.apis.paths.api_0_issues_issue_id_tags_key_ import Api0IssuesIssueIdTagsKey
from openapi_client.apis.paths.api_0_issues_issue_id_hashes_ import Api0IssuesIssueIdHashes
from openapi_client.apis.paths.api_0_issues_issue_id_events_oldest_ import Api0IssuesIssueIdEventsOldest
from openapi_client.apis.paths.api_0_issues_issue_id_events_latest_ import Api0IssuesIssueIdEventsLatest
from openapi_client.apis.paths.api_0_issues_issue_id_events_ import Api0IssuesIssueIdEvents
from openapi_client.apis.paths.api_0_issues_issue_id_ import Api0IssuesIssueId
from openapi_client.apis.paths.api_0_organizations_organization_slug_releases_ import Api0OrganizationsOrganizationSlugReleases
from openapi_client.apis.paths.api_0_organizations_organization_slug_releases_version_ import Api0OrganizationsOrganizationSlugReleasesVersion
from openapi_client.apis.paths.api_0_organizations_organization_slug_releases_version_files_ import Api0OrganizationsOrganizationSlugReleasesVersionFiles
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_releases_version_files_ import Api0ProjectsOrganizationSlugProjectSlugReleasesVersionFiles
from openapi_client.apis.paths.api_0_organizations_organization_slug_releases_version_files_file_id_ import Api0OrganizationsOrganizationSlugReleasesVersionFilesFileId
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_releases_version_files_file_id_ import Api0ProjectsOrganizationSlugProjectSlugReleasesVersionFilesFileId
from openapi_client.apis.paths.api_0_organizations_organization_slug_releases_version_commits_ import Api0OrganizationsOrganizationSlugReleasesVersionCommits
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_releases_version_commits_ import Api0ProjectsOrganizationSlugProjectSlugReleasesVersionCommits
from openapi_client.apis.paths.api_0_organizations_organization_slug_releases_version_commitfiles_ import Api0OrganizationsOrganizationSlugReleasesVersionCommitfiles
from openapi_client.apis.paths.api_0_projects_organization_slug_project_slug_releases_version_resolved_ import Api0ProjectsOrganizationSlugProjectSlugReleasesVersionResolved
from openapi_client.apis.paths.api_0_organizations_organization_slug_releases_version_deploys_ import Api0OrganizationsOrganizationSlugReleasesVersionDeploys
from openapi_client.apis.paths.api_0_organizations_organization_slug_sentry_app_installations_ import Api0OrganizationsOrganizationSlugSentryAppInstallations
from openapi_client.apis.paths.api_0_sentry_app_installations_uuid_external_issues_ import Api0SentryAppInstallationsUuidExternalIssues
from openapi_client.apis.paths.api_0_sentry_app_installations_uuid_external_issues_external_issue_id_ import Api0SentryAppInstallationsUuidExternalIssuesExternalIssueId

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.API_0_ORGANIZATION_ORGANIZATION_SLUG_MONITORS_MONITOR_SLUG_CHECKINS_: Api0OrganizationOrganizationSlugMonitorsMonitorSlugCheckins,
        PathValues.API_0_ORGANIZATION_ORGANIZATION_SLUG_MONITORS_MONITOR_SLUG_CHECKINS_CHECKIN_ID_: Api0OrganizationOrganizationSlugMonitorsMonitorSlugCheckinsCheckinId,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_EVENTS_: Api0OrganizationsOrganizationSlugEvents,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_MEMBERS_MEMBER_ID_: Api0OrganizationsOrganizationSlugMembersMemberId,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_MONITORS_: Api0OrganizationsOrganizationSlugMonitors,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_MONITORS_MONITOR_SLUG_: Api0OrganizationsOrganizationSlugMonitorsMonitorSlug,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_PROJECTS_: Api0OrganizationsOrganizationSlugProjects,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SCIM_V2_GROUPS: Api0OrganizationsOrganizationSlugScimV2Groups,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SCIM_V2_GROUPS_TEAM_ID: Api0OrganizationsOrganizationSlugScimV2GroupsTeamId,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SCIM_V2_USERS: Api0OrganizationsOrganizationSlugScimV2Users,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SCIM_V2_USERS_MEMBER_ID: Api0OrganizationsOrganizationSlugScimV2UsersMemberId,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_STATS_V2_: Api0OrganizationsOrganizationSlugStatsV2,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_EVENTS_EVENT_ID_SOURCEMAPDEBUG_: Api0ProjectsOrganizationSlugProjectSlugEventsEventIdSourceMapDebug,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_TEAMS_: Api0OrganizationsOrganizationSlugTeams,
        PathValues.API_0_TEAMS_ORGANIZATION_SLUG_TEAM_SLUG_: Api0TeamsOrganizationSlugTeamSlug,
        PathValues.API_0_TEAMS_ORGANIZATION_SLUG_TEAM_SLUG_PROJECTS_: Api0TeamsOrganizationSlugTeamSlugProjects,
        PathValues.API_0_TEAMS_ORGANIZATION_SLUG_TEAM_SLUG_STATS_: Api0TeamsOrganizationSlugTeamSlugStats,
        PathValues.API_0_ORGANIZATIONS_: Api0Organizations,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_EVENTIDS_EVENT_ID_: Api0OrganizationsOrganizationSlugEventidsEventId,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_: Api0OrganizationsOrganizationSlug,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_REPOS_: Api0OrganizationsOrganizationSlugRepos,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_REPOS_REPO_ID_COMMITS_: Api0OrganizationsOrganizationSlugReposRepoIdCommits,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_STATS_: Api0OrganizationsOrganizationSlugStats,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SESSIONS_: Api0OrganizationsOrganizationSlugSessions,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_USERS_: Api0OrganizationsOrganizationSlugUsers,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SHORTIDS_SHORT_ID_: Api0OrganizationsOrganizationSlugShortidsShortId,
        PathValues.API_0_PROJECTS_: Api0Projects,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_: Api0ProjectsOrganizationSlugProjectSlug,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_FILES_DSYMS_: Api0ProjectsOrganizationSlugProjectSlugFilesDsyms,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_USERS_: Api0ProjectsOrganizationSlugProjectSlugUsers,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_TAGS_KEY_VALUES_: Api0ProjectsOrganizationSlugProjectSlugTagsKeyValues,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_STATS_: Api0ProjectsOrganizationSlugProjectSlugStats,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_USERFEEDBACK_: Api0ProjectsOrganizationSlugProjectSlugUserFeedback,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_KEYS_: Api0ProjectsOrganizationSlugProjectSlugKeys,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_KEYS_KEY_ID_: Api0ProjectsOrganizationSlugProjectSlugKeysKeyId,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_HOOKS_: Api0ProjectsOrganizationSlugProjectSlugHooks,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_HOOKS_HOOK_ID_: Api0ProjectsOrganizationSlugProjectSlugHooksHookId,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_EVENTS_EVENT_ID_: Api0ProjectsOrganizationSlugProjectSlugEventsEventId,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_EVENTS_: Api0ProjectsOrganizationSlugProjectSlugEvents,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_ISSUES_: Api0ProjectsOrganizationSlugProjectSlugIssues,
        PathValues.API_0_ISSUES_ISSUE_ID_TAGS_KEY_VALUES_: Api0IssuesIssueIdTagsKeyValues,
        PathValues.API_0_ISSUES_ISSUE_ID_TAGS_KEY_: Api0IssuesIssueIdTagsKey,
        PathValues.API_0_ISSUES_ISSUE_ID_HASHES_: Api0IssuesIssueIdHashes,
        PathValues.API_0_ISSUES_ISSUE_ID_EVENTS_OLDEST_: Api0IssuesIssueIdEventsOldest,
        PathValues.API_0_ISSUES_ISSUE_ID_EVENTS_LATEST_: Api0IssuesIssueIdEventsLatest,
        PathValues.API_0_ISSUES_ISSUE_ID_EVENTS_: Api0IssuesIssueIdEvents,
        PathValues.API_0_ISSUES_ISSUE_ID_: Api0IssuesIssueId,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_: Api0OrganizationsOrganizationSlugReleases,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_: Api0OrganizationsOrganizationSlugReleasesVersion,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_FILES_: Api0OrganizationsOrganizationSlugReleasesVersionFiles,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_RELEASES_VERSION_FILES_: Api0ProjectsOrganizationSlugProjectSlugReleasesVersionFiles,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_FILES_FILE_ID_: Api0OrganizationsOrganizationSlugReleasesVersionFilesFileId,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_RELEASES_VERSION_FILES_FILE_ID_: Api0ProjectsOrganizationSlugProjectSlugReleasesVersionFilesFileId,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_COMMITS_: Api0OrganizationsOrganizationSlugReleasesVersionCommits,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_RELEASES_VERSION_COMMITS_: Api0ProjectsOrganizationSlugProjectSlugReleasesVersionCommits,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_COMMITFILES_: Api0OrganizationsOrganizationSlugReleasesVersionCommitfiles,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_RELEASES_VERSION_RESOLVED_: Api0ProjectsOrganizationSlugProjectSlugReleasesVersionResolved,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_DEPLOYS_: Api0OrganizationsOrganizationSlugReleasesVersionDeploys,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SENTRYAPPINSTALLATIONS_: Api0OrganizationsOrganizationSlugSentryAppInstallations,
        PathValues.API_0_SENTRYAPPINSTALLATIONS_UUID_EXTERNALISSUES_: Api0SentryAppInstallationsUuidExternalIssues,
        PathValues.API_0_SENTRYAPPINSTALLATIONS_UUID_EXTERNALISSUES_EXTERNAL_ISSUE_ID_: Api0SentryAppInstallationsUuidExternalIssuesExternalIssueId,
    }
)

path_to_api = PathToApi(
    {
        PathValues.API_0_ORGANIZATION_ORGANIZATION_SLUG_MONITORS_MONITOR_SLUG_CHECKINS_: Api0OrganizationOrganizationSlugMonitorsMonitorSlugCheckins,
        PathValues.API_0_ORGANIZATION_ORGANIZATION_SLUG_MONITORS_MONITOR_SLUG_CHECKINS_CHECKIN_ID_: Api0OrganizationOrganizationSlugMonitorsMonitorSlugCheckinsCheckinId,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_EVENTS_: Api0OrganizationsOrganizationSlugEvents,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_MEMBERS_MEMBER_ID_: Api0OrganizationsOrganizationSlugMembersMemberId,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_MONITORS_: Api0OrganizationsOrganizationSlugMonitors,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_MONITORS_MONITOR_SLUG_: Api0OrganizationsOrganizationSlugMonitorsMonitorSlug,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_PROJECTS_: Api0OrganizationsOrganizationSlugProjects,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SCIM_V2_GROUPS: Api0OrganizationsOrganizationSlugScimV2Groups,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SCIM_V2_GROUPS_TEAM_ID: Api0OrganizationsOrganizationSlugScimV2GroupsTeamId,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SCIM_V2_USERS: Api0OrganizationsOrganizationSlugScimV2Users,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SCIM_V2_USERS_MEMBER_ID: Api0OrganizationsOrganizationSlugScimV2UsersMemberId,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_STATS_V2_: Api0OrganizationsOrganizationSlugStatsV2,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_EVENTS_EVENT_ID_SOURCEMAPDEBUG_: Api0ProjectsOrganizationSlugProjectSlugEventsEventIdSourceMapDebug,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_TEAMS_: Api0OrganizationsOrganizationSlugTeams,
        PathValues.API_0_TEAMS_ORGANIZATION_SLUG_TEAM_SLUG_: Api0TeamsOrganizationSlugTeamSlug,
        PathValues.API_0_TEAMS_ORGANIZATION_SLUG_TEAM_SLUG_PROJECTS_: Api0TeamsOrganizationSlugTeamSlugProjects,
        PathValues.API_0_TEAMS_ORGANIZATION_SLUG_TEAM_SLUG_STATS_: Api0TeamsOrganizationSlugTeamSlugStats,
        PathValues.API_0_ORGANIZATIONS_: Api0Organizations,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_EVENTIDS_EVENT_ID_: Api0OrganizationsOrganizationSlugEventidsEventId,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_: Api0OrganizationsOrganizationSlug,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_REPOS_: Api0OrganizationsOrganizationSlugRepos,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_REPOS_REPO_ID_COMMITS_: Api0OrganizationsOrganizationSlugReposRepoIdCommits,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_STATS_: Api0OrganizationsOrganizationSlugStats,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SESSIONS_: Api0OrganizationsOrganizationSlugSessions,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_USERS_: Api0OrganizationsOrganizationSlugUsers,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SHORTIDS_SHORT_ID_: Api0OrganizationsOrganizationSlugShortidsShortId,
        PathValues.API_0_PROJECTS_: Api0Projects,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_: Api0ProjectsOrganizationSlugProjectSlug,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_FILES_DSYMS_: Api0ProjectsOrganizationSlugProjectSlugFilesDsyms,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_USERS_: Api0ProjectsOrganizationSlugProjectSlugUsers,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_TAGS_KEY_VALUES_: Api0ProjectsOrganizationSlugProjectSlugTagsKeyValues,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_STATS_: Api0ProjectsOrganizationSlugProjectSlugStats,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_USERFEEDBACK_: Api0ProjectsOrganizationSlugProjectSlugUserFeedback,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_KEYS_: Api0ProjectsOrganizationSlugProjectSlugKeys,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_KEYS_KEY_ID_: Api0ProjectsOrganizationSlugProjectSlugKeysKeyId,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_HOOKS_: Api0ProjectsOrganizationSlugProjectSlugHooks,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_HOOKS_HOOK_ID_: Api0ProjectsOrganizationSlugProjectSlugHooksHookId,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_EVENTS_EVENT_ID_: Api0ProjectsOrganizationSlugProjectSlugEventsEventId,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_EVENTS_: Api0ProjectsOrganizationSlugProjectSlugEvents,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_ISSUES_: Api0ProjectsOrganizationSlugProjectSlugIssues,
        PathValues.API_0_ISSUES_ISSUE_ID_TAGS_KEY_VALUES_: Api0IssuesIssueIdTagsKeyValues,
        PathValues.API_0_ISSUES_ISSUE_ID_TAGS_KEY_: Api0IssuesIssueIdTagsKey,
        PathValues.API_0_ISSUES_ISSUE_ID_HASHES_: Api0IssuesIssueIdHashes,
        PathValues.API_0_ISSUES_ISSUE_ID_EVENTS_OLDEST_: Api0IssuesIssueIdEventsOldest,
        PathValues.API_0_ISSUES_ISSUE_ID_EVENTS_LATEST_: Api0IssuesIssueIdEventsLatest,
        PathValues.API_0_ISSUES_ISSUE_ID_EVENTS_: Api0IssuesIssueIdEvents,
        PathValues.API_0_ISSUES_ISSUE_ID_: Api0IssuesIssueId,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_: Api0OrganizationsOrganizationSlugReleases,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_: Api0OrganizationsOrganizationSlugReleasesVersion,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_FILES_: Api0OrganizationsOrganizationSlugReleasesVersionFiles,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_RELEASES_VERSION_FILES_: Api0ProjectsOrganizationSlugProjectSlugReleasesVersionFiles,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_FILES_FILE_ID_: Api0OrganizationsOrganizationSlugReleasesVersionFilesFileId,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_RELEASES_VERSION_FILES_FILE_ID_: Api0ProjectsOrganizationSlugProjectSlugReleasesVersionFilesFileId,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_COMMITS_: Api0OrganizationsOrganizationSlugReleasesVersionCommits,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_RELEASES_VERSION_COMMITS_: Api0ProjectsOrganizationSlugProjectSlugReleasesVersionCommits,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_COMMITFILES_: Api0OrganizationsOrganizationSlugReleasesVersionCommitfiles,
        PathValues.API_0_PROJECTS_ORGANIZATION_SLUG_PROJECT_SLUG_RELEASES_VERSION_RESOLVED_: Api0ProjectsOrganizationSlugProjectSlugReleasesVersionResolved,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_RELEASES_VERSION_DEPLOYS_: Api0OrganizationsOrganizationSlugReleasesVersionDeploys,
        PathValues.API_0_ORGANIZATIONS_ORGANIZATION_SLUG_SENTRYAPPINSTALLATIONS_: Api0OrganizationsOrganizationSlugSentryAppInstallations,
        PathValues.API_0_SENTRYAPPINSTALLATIONS_UUID_EXTERNALISSUES_: Api0SentryAppInstallationsUuidExternalIssues,
        PathValues.API_0_SENTRYAPPINSTALLATIONS_UUID_EXTERNALISSUES_EXTERNAL_ISSUE_ID_: Api0SentryAppInstallationsUuidExternalIssuesExternalIssueId,
    }
)
